version: '3'

services:
  gp1f5a1:
    image: gp1f5a1:1.0
    expose:
      - "80"
    environment:
      HOST_NAME: gp1f5a1.fjeclot.net

  lb:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gp1f5a1
    ports:
      - "80:8000"