IMATGE_BOX = "debian/bookworm64"
NOM_NODE = "desenvolupador-gp1f5a1"
MEMORIA = 2048
CPUS = 2
#TARGETA_XARXA = "Intel(R) Wireless-AC 9560 160MHz"
TARGETA_XARXA = "Realtek PCIe GbE Family Controller"
Vagrant.configure("2") do |config|
 config.vm.box = IMATGE_BOX
 config.vm.hostname = NOM_NODE
 config.vm.network "public_network", bridge: TARGETA_XARXA
 config.vm.provider "virtualbox" do |v|
 v.name = NOM_NODE
 v.memory = MEMORIA
 v.cpus = CPUS
 v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
 end
 config.vm.synced_folder "A:/Jesuites Treballs/Cicle Superior/3r any ASIX/GP1/projectes/gp1f5a1", "/home/vagrant/desenvolupaments"
 config.vm.provision "shell", inline: <<-SHELL
 sudo apt-get update -y
 sudo apt-get install -y net-tools
 sudo apt-get install -y whois
 sudo apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
 curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
 sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
 sudo apt-get update -y
 sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose
 sudo gpasswd -a vagrant docker
 exit
 SHELL
end